# Conversation Catalog Configuration
# This file contains metadata for scenarios, workflows, and CJ versions
# Used for discovery and UI presentation
# NOTE: Persona data is now managed by PersonaService

workflows:
  shopify_onboarding:
    name: shopify_onboarding
    display_name: Shopify Onboarding
    description: Natural conversation flow for new visitors. CJ guides through Shopify connection and optional support system setup.
    typical_turns: 6
    initiator: CJ
    best_for:
      - new_visitors
      - returning_visitors_without_auth
    features:
      - natural_detection
      - oauth_integration
      - progressive_disclosure
  
  daily_briefing:
    name: daily_briefing
    display_name: Daily Flash Report
    description: CJ sends morning metrics report with insights. Great for data-driven merchants who want regular updates.
    typical_turns: 3
    initiator: CJ
    best_for:
      - growth_stall
      - return_to_growth
      - scaling_chaos

  crisis_response:
    name: crisis_response
    display_name: Crisis Management
    description: CJ helps navigate urgent business crisis with rapid-fire support and actionable solutions.
    typical_turns: 5
    initiator: merchant
    best_for:
      - churn_spike
      - scaling_chaos

  ad_hoc_support:
    name: ad_hoc_support
    display_name: Ad-hoc Chat
    description: Organic conversation flow. Merchant brings up whatever's on their mind.
    typical_turns: 4
    initiator: merchant
    best_for:
      - all scenarios

  weekly_review:
    name: weekly_review
    display_name: Weekly Business Review
    description: Comprehensive weekly performance analysis with strategic recommendations.
    typical_turns: 4
    initiator: CJ
    best_for:
      - growth_stall
      - competitor_threat
      - return_to_growth

cj_versions:
  v6.0.1: Autonomous - CX & Growth Officer, outcome-focused, time-respecting (fixed)
  v6.0.0: Autonomous - CX & Growth Officer, outcome-focused (has template issues)
  v5.0.0: Human-like - Adapts to merchant stress levels, team member voice
  v4.0.0: Stable - Balanced helpfulness and boundaries
  v3.0.0: Classic - More formal, tool-focused responses
  v2.0.0: Legacy - Original personality, less adaptive
  v1.0.0: Basic - Simple responses, minimal personality

recommended_combinations:
  - name: Data-Driven Crisis
    merchant: marcus_thompson
    scenario: churn_spike
    workflow: crisis_response
    description: Watch Marcus's terse style escalate during quality crisis

  - name: Thoughtful Growth Planning
    merchant: sarah_chen
    scenario: growth_stall
    workflow: weekly_review
    description: Sarah's methodical approach to solving growth challenges

  - name: Influencer Overwhelm
    merchant: zoe_martinez
    scenario: scaling_chaos
    workflow: daily_briefing
    description: Zoe trying to maintain zen while everything's on fire

  - name: Competitive Panic
    merchant: marcus_thompson
    scenario: competitor_threat
    workflow: chat
    description: Marcus discovers a well-funded competitor

  - name: Values vs Reality
    merchant: sarah_chen
    scenario: return_to_growth
    workflow: weekly_review
    description: Sarah balancing sustainability with growth pressure
