metadata:
  version: 1.0.0
  description: "Configuration values for fact-checking system"

cache:
  ttl_seconds: 300  # 5 minutes default
  max_entries: 100  # Maximum cache size

async_execution:
  max_workers: 2  # Thread pool size
  default_timeout: 5.0  # Default wait timeout in seconds
  max_timeout: 30.0  # Maximum wait timeout for interactive mode

api:
  temperature: 0.1  # Low temperature for consistency
  max_tokens: 4000  # Enough for detailed analysis
  response_format: "json_object"  # Force JSON mode

thresholds:
  minor_variation_percent: 10  # ±10% allowed for minor variations
  major_error_percent: 25  # >25% difference is major error

evaluation_modes:
  strict_mode: false  # Whether to use strict fact checking by default

verification_focus:
  - "revenue"
  - "subscribers"
  - "percentages"
  - "ticket_counts"
  - "customer_names"
  - "timeline_dates"
  - "support_metrics"
  - "business_metrics"
