#!/bin/bash
# ================================================
# Clean up old .env files - Phase 4.0
# ================================================
# This script removes all service-specific env files that 
# developers should no longer edit directly
# ================================================

echo "🧹 Cleaning up old .env files..."
echo "This will remove service-specific env files that are now auto-generated."
echo ""

# Counter for removed files
removed=0

# Function to safely remove a file
remove_if_exists() {
    if [ -f "$1" ]; then
        echo "  ❌ Removing: $1"
        rm -f "$1"
        ((removed++))
    fi
}

echo "📁 Cleaning auth service..."
remove_if_exists "auth/.env.local"
remove_if_exists "auth/.env.secrets"
remove_if_exists "auth/.env.tunnel"
remove_if_exists "auth/.env.example"
remove_if_exists "auth/.env.secrets.example"

echo ""
echo "📁 Cleaning agents service..."
remove_if_exists "agents/.env.local"  
remove_if_exists "agents/.env.secrets"
remove_if_exists "agents/.env.tunnel"
remove_if_exists "agents/.env.example"

echo ""
echo "📁 Cleaning database service..."
remove_if_exists "database/.env.local"
remove_if_exists "database/.env.secrets"
remove_if_exists "database/.env.tunnel"
remove_if_exists "database/.env.example"

echo ""
echo "📁 Cleaning homepage service..."
remove_if_exists "homepage/.env.local"
remove_if_exists "homepage/.env.secrets"
remove_if_exists "homepage/.env.tunnel"
remove_if_exists "homepage/.env.example"
remove_if_exists "homepage/.env.minimal"

echo ""
echo "📁 Cleaning root directory..."
# Don't remove root .env.local as it might have user overrides
# remove_if_exists ".env.local"

# Keep .env.tunnel at root as it's auto-generated by detect_tunnels.py

echo ""
echo "✅ Cleanup complete - removed $removed files"
echo ""
echo "📝 Note: The following files are kept:"
echo "   - .env (your master configuration)"
echo "   - .env.tunnel (auto-generated tunnel URLs)"
echo "   - Service .env files (auto-generated by distribute_env.py)"
echo ""
echo "🚀 Next steps:"
echo "   1. Make sure your .env file has all needed variables"
echo "   2. Run 'python scripts/distribute_env.py' to generate service .env files"
echo "   3. Start services with 'make dev'"