# Base eval configuration for HireCJ
# All other evals can inherit from these base configurations

base_eval:
  # Default timeout for all evals
  timeout: 30
  
  # Default number of retries
  retries: 3
  
  # Default concurrency for parallel execution
  workers: 4
  
  # Default metrics to track
  default_metrics:
    - latency
    - success_rate
    - tokens_used


# Base eval for exact matching
exact_match:
  parent: base_eval
  class: evals.base.ExactMatch
  args:
    case_sensitive: false
    strip_whitespace: true


# Base eval for fuzzy matching
fuzzy_match:
  parent: base_eval
  class: evals.base.FuzzyMatch
  args:
    threshold: 0.8
    algorithm: levenshtein


# Base eval for includes checking
includes_eval:
  parent: base_eval
  class: evals.base.Includes
  args:
    case_sensitive: false
    all_required: true


# Base eval for model-graded responses
model_graded:
  parent: base_eval
  class: evals.base.ModelGraded
  args:
    grader_model: gpt-4
    temperature: 0.0
    max_tokens: 100